#config ;-P
lobby: lobby
playersperteam: 4
roundtime: 10
Spawnlocation:
  x: 92.5
  y: 73.0
  z: 189.5
  world: world
  yaw: 180.0
  pitch: 0.0
Lobbyspawnlocation:
  x: 2.5
  y: 64
  z: -0.5
  world: lobby
  yaw: 0.0
  pitch: 0.0