#config ;-P
lobby: lobby
playersperteam: 4
roundtime: 10
Spawnlocation:
  x: 92.5
  y: 73.0
  z: 189.5
  world: world
  yaw: 180.0
  pitch: 0.0
Lobbyspawnlocation:
  x: -1.5
  y: 65
  z: 0.5
  world: waitinglobby
  yaw: -90.0
  pitch: 0.0